CONSUL - GET Key:
  policy: "Enterprise/MasterTemplate/Consul - GET Key"
  arguments:
  - name: "endPointCalling"
    type: "string"
    requireExplicit: true
  results:
  - name: "output"
    type: "message"
  properties:
    paletteFolder: "internalAssertions"
    allowTracing: "true"
    description: "Retreive Value for a given Key from Consul Key/Value Stream"
    passMetricsToParent: "true"
CONSUL - Dynamic Route with Key:
  policy: "Enterprise/MasterTemplate/Consul - Dynamic Route with Key"
  arguments:
  - name: "endPointCalling"
    type: "string"
    requireExplicit: true
  results: []
  properties:
    paletteFolder: "internalAssertions"
    allowTracing: "true"
    description: "Retrieves specifc key/value from Consul and does a dynamic Route"
    passMetricsToParent: "true"
CONSUL - DeRegister Catalog Service:
  policy: "Enterprise/MasterTemplate/Consul - DeRegister Catalog"
  arguments: []
  results: []
  properties:
    paletteFolder: "internalAssertions"
    allowTracing: "false"
    description: "Consul Deregister Service"
    passMetricsToParent: "false"
CONSUL - Catalog Register:
  policy: "Enterprise/MasterTemplate/Consul - Catalog Register"
  arguments: []
  results: []
  properties:
    paletteFolder: "internalAssertions"
    allowTracing: "false"
    description: "For Registering Service with catalog"
    passMetricsToParent: "false"
Consul - Dynamic Route with Service:
  policy: "Enterprise/MasterTemplate/Consul - Dynamic Route with Service"
  arguments:
  - name: "endPointCalling"
    type: "string"
    requireExplicit: true
  results: []
  properties:
    paletteFolder: "internalAssertions"
    allowTracing: "false"
    description: "Dynamic Route for Service in Catalog (consul)"
    passMetricsToParent: "false"
CONSUL - Catalog Search:
  policy: "Enterprise/MasterTemplate/Consul - Catalog Search"
  arguments:
  - name: "endPointCalling"
    type: "string"
    requireExplicit: true
  results: []
  properties:
    paletteFolder: "internalAssertions"
    allowTracing: "false"
    description: "Search the catalog based on input \n a. No input - brings all services\
      \ in the catalog\n b. with specific service given - brings the details for that\
      \ service."
    passMetricsToParent: "false"
JWT - Validate:
  policy: "Enterprise/MasterTemplate/JWT - VALIDATE"
  arguments: []
  results: []
  properties:
    paletteFolder: "internalAssertions"
    allowTracing: "false"
    description: "JWT Validation Policy for the given set of keys"
    passMetricsToParent: "false"
CONSUL - Apply RateLimit:
  policy: "Enterprise/MasterTemplate/Consul - Apply RateLimit"
  arguments:
  - name: "domain"
    type: "string"
    requireExplicit: true
  results: []
  properties:
    paletteFolder: "accessControl"
    allowTracing: "true"
    description: "Applying Rate Limit specific to given Domain using Consul Key/Value\
      \ Stream."
    passMetricsToParent: "true"
CONSUL - PUT Key:
  policy: "Enterprise/MasterTemplate/Consul - PUT Key"
  arguments:
  - name: "endPointCalling"
    type: "string"
    requireExplicit: true
  results: []
  properties:
    paletteFolder: "internalAssertions"
    allowTracing: "true"
    description: "Adding/Updating the Key/Value Stream in Consul"
    passMetricsToParent: "true"
JWT-Validate:
  policy: "Enterprise/MasterTemplate/JWT-Validate"
  arguments: []
  results: []
  properties:
    paletteFolder: "internalAssertions"
    allowTracing: "false"
    description: "JWT Validation Policy for the given set of keys"
    passMetricsToParent: "false"
